### ISSUE TITLE
Problems playing through extremely large journals

### ISSUE THREAD

**Issue by jasongoodwin** [WegenenVerkeer/akka-persistence-postgresql#20]
I've been investigating problems playing through extraordinarily large aggregate journals.

https://github.com/funnelcloudinc/akka-persistence-postgresql/commit/f93803eaf1986e9cd300314e2a0407ce4be076c1

I implemented pagination. I'm still finding there is some kind of growth during the recovery period into very large numbers of events (eg 10M)

There seems to be something related to the items that hang around somehow. I'm investigating.

**Comment by kwark** [comment]
Hi Jason,

Are you using version 0.9.0 or later?

It should contain this commit: https://github.com/WegenenVerkeer/akka-persistence-postgresql/commit/74596afef4fb760efaa9769a19241ef7df5a75c6#diff-e2f0b6b1898906ec9fcbc7afba19fc4cR106 which does the streaming correctly when replaying a large number of journal entries.

**Comment by kwark** [comment]
I should probably write a test-case for this streaming recovery in order to check that it really works.
