### ISSUE TITLE
Upgrade slick to 3.3.0

### ISSUE THREAD

**Issue by fg-devs** [WegenenVerkeer/akka-persistence-postgresql#38]
Update slick to latest version (3.3.0) which uses one of the lastet versions of hikaricp (3.x).

**Comment by fg-devs** [comment]
@kwark Would it be possible that you create a new release (0.12.0) after this PR?

**Comment by kwark** [comment]
fixed by https://github.com/WegenenVerkeer/akka-persistence-postgresql/pull/39
and version 0.12.0 is released on sonatype
